[package]
name = "rs_space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lemurs = { path = "../lemurs/_8080", package = "_8080"}
sdl2 = { version = ">= 0.35.2", features = ["bundled"] }
